# Generated by Django 5.1.7 on 2025-06-28 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='residential_complex',
        ),
        migrations.AddField(
            model_name='apartments',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.neighborhoods', verbose_name='ЖК'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='sales',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.sales', verbose_name='Застройщик'),
        ),
        migrations.AddField(
            model_name='neighborhoods',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.developers', verbose_name='Застройщик'),
        ),
    ]
