# Generated by Django 5.1.7 on 2025-06-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_apartments_residential_complex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название скидки'),
        ),
    ]
