# Generated by Django 5.1.7 on 2025-06-28 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_sales_options_alter_sales_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartments',
            old_name='area',
            new_name='total_area',
        ),
        migrations.AddField(
            model_name='apartments',
            name='is_house_done',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=64, null=True, verbose_name='Сдан ли дом?'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='kitchen_area',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Площадь (кв.м)'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='living_area',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Площадь (кв.м)'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='mortgage',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=64, null=True, verbose_name='Ипотека'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='offer_model',
            field=models.CharField(choices=[('none', 'Без отделки'), ('rough', 'Черновая'), ('fine', 'Чистовая'), ('designer', 'Дизайнерская')], max_length=64, null=True, verbose_name='Тип сделки'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='price_difference_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Отклонение от рыночной цены (%)'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='price_per_sqm',
            field=models.PositiveIntegerField(verbose_name='Цена за квадратный метр'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='sales',
            field=models.ManyToManyField(blank=True, to='mainapp.sales', verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='Текущая общая цена'),
        ),
    ]
