# Generated by Django 5.1.7 on 2025-06-28 15:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название застройщика')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг застройщика')),
                ('reviews', models.IntegerField(default=0, verbose_name='Количество отзывов')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('projects_in_progress', models.IntegerField(default=0, verbose_name='Количество проектов в работе')),
                ('projects_completed', models.IntegerField(default=0, verbose_name='Количество завершенных проектов')),
                ('year', models.PositiveIntegerField(verbose_name='Год основания')),
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
            },
        ),
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название жилого комплекса')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('reviews', models.IntegerField(default=0, verbose_name='Количество отзывов')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('number_of_apartments', models.IntegerField(default=0, verbose_name='Количество квартир')),
            ],
            options={
                'verbose_name': 'Жилой комплекс',
                'verbose_name_plural': 'Жилые комплексы',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продажи')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Текущая общая цена')),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за квадратный метр')),
                ('price_difference_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Отклонение от рыночной цены (%)')),
                ('rooms', models.PositiveSmallIntegerField(help_text='Для студии укажите 0', verbose_name='Количество комнат')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь (кв.м)')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('total_floors', models.PositiveSmallIntegerField(verbose_name='Всего этажей в доме')),
                ('finishing', models.CharField(choices=[('none', 'Без отделки'), ('rough', 'Черновая'), ('fine', 'Чистовая'), ('designer', 'Дизайнерская')], max_length=20, verbose_name='Тип отделки')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.developers', verbose_name='Застройщик')),
                ('residential_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.neighborhoods', verbose_name='Жилой комплекс')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['-created_at'],
            },
        ),
    ]
