# Generated by Django 5.1.7 on 2025-06-28 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_apartments_residential_complex_and_more'),
        ('users', '0003_customer_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Неизвестно', max_length=128),
        ),
        migrations.AddField(
            model_name='customer',
            name='kids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='marriage',
            field=models.TextField(default='Неизвестно', max_length=15),
        ),
        migrations.AlterField(
            model_name='developer',
            name='company_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.developers'),
        ),
    ]
